### PR TITLE
Add new option `--seed`, and remove `--random`.

### PR DESCRIPTION
**Pull request by mazznoer**
This will make `lolcat` behave the same as `ruby-lolcat`.

### CODE REVIEW

**Comment by jaseg** [comment]
Thanks for the PR, but it's ok if c-lolcat behaves differently. What is the use case for ```--seed```, where ```--random``` isn't enough?

**Comment by 13-05** [comment]
@jaseg i use `--seed` in the original lolcat to get a certain color spread, `--seed=22` ensures that i always get a purple-blue spread, etc. `--random` is just that, random. i know im not a contributor but i think this pr should be merged

maybe dont entirely remove `--random`, tho. both should be fine, right?

**Comment by mazznoer** [comment]
Please note that this just remove `--random` flag, but not the random functionality. If `--seed` is not specified, or if `--seed 0` , that is the same as `--random`.

**Comment by jaseg** [comment]
Thank you for the PR! Merged in 37bb84e2977265331503236ed78d39ca04352226. I decided to keep `--random` for backwards-compatibility. `--seed 0` does now just seed with `srand(0)`, `--random` without `--seed` produces random colors.

**Pull request closed without merging**
