### PR TITLE
Autotoolize: use autotools intead of static Makefile

### PR DESCRIPTION
**Pull request by daniel-santos**
Hello!

Thanks for this. I just discovered the original lolcat a few days ago and I was fortunate enough to find an implementation in C!  I'm planning on trying to sneak it onto a router my company makes, but I needed it autotool-ized because we cross compile and all of that.  So if you want it, then here it is!

Some maintainers like to bundle the autotools-generated code in their repositories, but I'm not one of those.  So it requires autoconf and automake.  If you prefer not to require that, then you can run autogen.sh, but change the last command to `automake --add-missing --copy` so it will copy the template scripts instead of symlink them -- then just add the result to the repo.

### CODE REVIEW

**Comment by ryandesign** [comment]
> I chose a simple Makefile for this project because it does the job, no more, no less.

—badly. See #56 and #57. Manually writing a Makefile that does everything everyone expects is hard. That's why we use autotools or other build systems.

**Comment by jaseg** [comment]
@ryandesign This repo has been on github for ten years now, and exactly two people have complained about the Makefile so far. 

Feel free to use whatever build system you want on your own hobby projects, but don't annoy me with your build system opinions when it's clear I'm not interested.

I'll see to fixing the issues you found in the Makefile, thanks for reporting them. But I'm not open to the attitude you show in this closed PR, and I'll block you if that repeats.

**Comment by ryandesign** [comment]
I apologize. I am a manager of the MacPorts project. Someone filed a ticket with us requesting that we add a port for your software. While attempting to do that, I noticed the problems with your Makefile and reported them. I interact with so many different software projects through MacPorts that I don't always take the time to phrase my messages in the most diplomatic way and for that I am sorry.

**Comment by jaseg** [comment]
@ryandesign Thank you. I can see how maintaining something like that your pain threshold for shitty makefiles might be different from the general population lol. I hope with the latest changes this is closer to what you like to work with.

**Comment by ryandesign** [comment]
I went with the autotools build system to avoid the problems but the changes look good and I agree that it is nice to avoid the time overhead of autotools so I'll try switching to the plain Makefile with the next version update.

**Pull request closed without merging**
